### ISSUE TITLE
http://city.shaform.com/blog/2016/11/05/detect-cats-with-tensorbox.html 关于一些疑问

### ISSUE THREAD

**Issue by qilicun** [shaform/experiments#3]
您好，
我刚看到您的博客，想自己尝试一下，但是有一点不是很明白，在博客里的grid height 和grid weight 为什么都要设置为19呢？这两个变量具体起到什么作用？ 望回复，谢谢！

**Comment by shaform** [comment]
根據 https://github.com/TensorBox/TensorBox/issues/45 ，他們等於 image_height/ 32 & image_width / 32

**Comment by qilicun** [comment]
谢谢！
